version: 0.2
phases:
 install:
   runtime-versions:
     python: 3.7
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - zip -r9 function.zip .
     - aws s3 sync . "s3://ujwaltest-codedeploy" --exclude "*.*" --include "*.zip" --delete
 post_build:
   commands:
     - echo "post_build step"
